const countryData = {
  AD: { name: "Andorra", length: 24 },
  AE: { name: "United Arab Emirates", length: 23 },
  AL: { name: "Albania", length: 28 },
  AT: { name: "Austria", length: 20 },
  AZ: { name: "Azerbaijan", length: 28 },
  BA: { name: "Bosnia and Herzegovina", length: 20 },
  BE: { name: "Belgium", length: 16 },
  BG: { name: "Bulgaria", length: 22 },
  BH: { name: "Bahrain", length: 22 },
  BR: { name: "Brazil", length: 29 },
  BY: { name: "Belarus", length: 28 },
  CH: { name: "Switzerland", length: 21 },
  CR: { name: "Costa Rica", length: 22 },
  CY: { name: "Cyprus", length: 28 },
  CZ: { name: "Czech Republic", length: 24 },
  DE: { name: "Germany", length: 22 },
  DK: { name: "Denmark", length: 18 },
  DO: { name: "Dominican Republic", length: 28 },
  EE: { name: "Estonia", length: 20 },
  EG: { name: "Egypt", length: 29 },
  ES: { name: "Spain", length: 24 },
  FI: { name: "Finland", length: 18 },
  FO: { name: "Faroe Islands", length: 18 },
  FR: { name: "France", length: 27 },
  GB: { name: "United Kingdom", length: 22 },
  GE: { name: "Georgia", length: 22 },
  GI: { name: "Gibraltar", length: 23 },
  GL: { name: "Greenland", length: 18 },
  GR: { name: "Greece", length: 27 },
  GT: { name: "Guatemala", length: 28 },
  HR: { name: "Croatia", length: 21 },
  HU: { name: "Hungary", length: 28 },
  IE: { name: "Ireland", length: 22 },
  IL: { name: "Israel", length: 23 },
  IS: { name: "Iceland", length: 26 },
  IT: { name: "Italy", length: 27 },
  JO: { name: "Jordan", length: 30 },
  KW: { name: "Kuwait", length: 30 },
  KZ: { name: "Kazakhstan", length: 20 },
  LB: { name: "Lebanon", length: 28 },
  LC: { name: "Saint Lucia", length: 32 },
  LI: { name: "Liechtenstein", length: 21 },
  LT: { name: "Lithuania", length: 20 },
  LU: { name: "Luxembourg", length: 20 },
  LV: { name: "Latvia", length: 21 },
  MC: { name: "Monaco", length: 27 },
  MD: { name: "Moldova", length: 24 },
  ME: { name: "Montenegro", length: 22 },
  MK: { name: "North Macedonia", length: 19 },
  MR: { name: "Mauritania", length: 27 },
  MT: { name: "Malta", length: 31 },
  MU: { name: "Mauritius", length: 30 },
  NL: { name: "Netherlands", length: 18 },
  NO: { name: "Norway", length: 15 },
  PK: { name: "Pakistan", length: 24 },
  PL: { name: "Poland", length: 28 },
  PS: { name: "Palestine", length: 29 },
  PT: { name: "Portugal", length: 25 },
  QA: { name: "Qatar", length: 29 },
  RO: { name: "Romania", length: 24 },
  RS: { name: "Serbia", length: 22 },
  SA: { name: "Saudi Arabia", length: 24 },
  SE: { name: "Sweden", length: 24 },
  SI: { name: "Slovenia", length: 19 },
  SK: { name: "Slovakia", length: 24 },
  SM: { name: "San Marino", length: 27 },
  TN: { name: "Tunisia", length: 24 },
  TR: { name: "Turkey", length: 26 },
  UA: { name: "Ukraine", length: 29 },
  VG: { name: "British Virgin Islands", length: 24 },
  XK: { name: "Kosovo", length: 20 }
};

const ibanStructures = {
  AD: { bankCode: [4, 8], branchCode: [8, 12], account: [12, 24] },
  AE: { bankCode: [4, 7], account: [7, 23] },
  AL: { bankCode: [4, 11], branchCode: [11, 15], account: [15, 28] },
  AT: { bankCode: [4, 9], account: [9, 20] },
  AZ: { bankCode: [4, 8], account: [8, 28] },
  BA: { bankCode: [4, 7], branchCode: [7, 13], account: [13, 20] },
  BE: { bankCode: [4, 7], account: [7, 16] },
  BG: { bankCode: [4, 8], branchCode: [8, 12], account: [12, 22] },
  BH: { bankCode: [4, 8], account: [8, 22] },
  BR: { bankCode: [4, 12], branchCode: [12, 17], account: [17, 27] },
  BY: { bankCode: [4, 8], branchCode: [8, 12], account: [12, 28] },
  CH: { bankCode: [4, 9], account: [9, 21] },
  CR: { bankCode: [4, 8], account: [8, 22] },
  CY: { bankCode: [4, 7], branchCode: [7, 12], account: [12, 28] },
  CZ: { bankCode: [4, 8], account: [8, 24] },
  DE: { bankCode: [4, 12], account: [12, 22] },
  DK: { bankCode: [4, 8], account: [8, 18] },
  DO: { bankCode: [4, 8], account: [8, 28] },
  EE: { bankCode: [4, 6], branchCode: [6, 8], account: [8, 20] },
  EG: { bankCode: [4, 8], branchCode: [8, 12], account: [12, 29] },
  ES: { bankCode: [4, 8], branchCode: [8, 12], account: [14, 24] },
  FI: { bankCode: [4, 10], account: [10, 18] },
  FO: { bankCode: [4, 8], account: [8, 18] },
  FR: { bankCode: [4, 9], branchCode: [9, 14], account: [14, 25] },
  GB: { bankCode: [4, 8], branchCode: [8, 14], account: [14, 22] },
  GE: { bankCode: [4, 6], account: [6, 22] },
  GI: { bankCode: [4, 8], account: [8, 23] },
  GL: { bankCode: [4, 8], account: [8, 18] },
  GR: { bankCode: [4, 7], branchCode: [7, 11], account: [11, 27] },
  GT: { bankCode: [4, 8], account: [8, 28] },
  HR: { bankCode: [4, 11], account: [11, 21] },
  HU: { bankCode: [4, 7], branchCode: [7, 11], account: [12, 28] },
  IE: { bankCode: [4, 8], branchCode: [8, 14], account: [14, 22] },
  IL: { bankCode: [4, 7], branchCode: [7, 10], account: [10, 23] },
  IS: { bankCode: [4, 8], branchCode: [8, 10], account: [10, 26] },
  IT: { bankCode: [5, 10], branchCode: [10, 15], account: [15, 27] },
  JO: { bankCode: [4, 8], branchCode: [8, 12], account: [12, 30] },
  KW: { bankCode: [4, 8], account: [8, 30] },
  KZ: { bankCode: [4, 7], account: [7, 20] },
  LB: { bankCode: [4, 8], account: [8, 28] },
  LC: { bankCode: [4, 8], account: [8, 32] },
  LI: { bankCode: [4, 9], account: [9, 21] },
  LT: { bankCode: [4, 9], account: [9, 20] },
  LU: { bankCode: [4, 7], account: [7, 20] },
  LV: { bankCode: [4, 8], account: [8, 21] },
  MC: { bankCode: [4, 9], branchCode: [9, 14], account: [14, 25] },
  MD: { bankCode: [4, 6], account: [6, 24] },
  ME: { bankCode: [4, 7], account: [7, 20] },
  MK: { bankCode: [4, 7], account: [7, 17] },
  MR: { bankCode: [4, 9], branchCode: [9, 14], account: [14, 27] },
  MT: { bankCode: [4, 8], branchCode: [8, 13], account: [13, 31] },
  MU: { bankCode: [4, 8], branchCode: [8, 14], account: [14, 28] },
  NL: { bankCode: [4, 8], account: [8, 18] },
  NO: { bankCode: [4, 8], account: [8, 15] },
  PK: { bankCode: [4, 8], account: [8, 24] },
  PL: { bankCode: [4, 12], account: [12, 28] },
  PS: { bankCode: [4, 8], account: [8, 29] },
  PT: { bankCode: [4, 8], branchCode: [8, 12], account: [12, 25] },
  QA: { bankCode: [4, 8], account: [8, 29] },
  RO: { bankCode: [4, 8], account: [8, 24] },
  RS: { bankCode: [4, 7], account: [7, 20] },
  SA: { bankCode: [4, 6], account: [6, 24] },
  SE: { bankCode: [4, 7], account: [7, 24] },
  SI: { bankCode: [4, 9], account: [9, 17] },
  SK: { bankCode: [4, 8], account: [8, 24] },
  SM: { bankCode: [5, 10], branchCode: [10, 15], account: [15, 27] },
  TN: { bankCode: [4, 6], branchCode: [6, 9], account: [9, 24] },
  TR: { bankCode: [4, 9], account: [9, 26] },
  UA: { bankCode: [4, 10], account: [10, 29] },
  VG: { bankCode: [4, 8], account: [8, 24] },
  XK: { bankCode: [4, 6], branchCode: [6, 8], account: [8, 20] }
};
